---
site:
  code: ffnord
  tld:  ffnord # optional, defaults to code
  mesh:
    network:
      ipv4: 10.187.0.0/17
      ipv6: fd42:eb49:c0b5:4242::/64
    network_dynamic_clients: # optional, defaults to network.ipv6
      ipv6: fd42:eb49:c0b5:4242::/64

  mesh_vpn:
    peer_limit: 300 # optional, defaults to no limit
    mtu: 1280
    key_git: https://github.com/Freifunk-Nord/nord-gw-peers.git
    port: 10050
    verify: no # optional, defaults to yes
    #ci_deploy_key: ''

  bgp:
    as: 65187

  dns:
    ffnord:
      git: https://github.com/Freifunk-Nord/nord-zone.git
      servers:
        - 127.0.0.1@5300
        - ::1@5300

  noc_keys:
    git: https://github.com/Freifunk-Nord/nord-noc-sshkeys.git

batman:
  version_min: 2015
