---
- name: Ensure manual config for interface {{ iface }} exists
  template:
    src: '{{ "etc/network/interfaces.d/{{ iface }}.j2" }}'
    dest: /etc/network/interfaces.d/{{ iface | regex_replace('\.', '') }}
  notify:
    - restart manual interface
  tags: interface_manual

- name: Check if interface {{ iface }} is down
  shell: ip link show {{ iface }} | grep -q 'state DOWN'
  check_mode: no
  register: iface_down
  failed_when: no
  tags: interface_manual

- name: Ensure {{ iface }} is up
  shell: |
    ifdown {{ iface }} || true
    ifup {{ iface }}
  when: 'iface_down.rc == 0'
  tags: interface_manual
