---
# Interface config
- name: Ensure ffnw ipv4 peering interface config is in place
  template:
    src: etc/network/interfaces.d/ffnw-gre_nat.j2
    dest: /etc/network/interfaces.d/ffnw-gre_nat
  notify:
    - restart ffnw tunnel
  tags: ffnw4

# bgp Peerings
- name: Ensure ffnw bgp4 peers are in place
  template:
    src: etc/bird/bird4.peers.d/ffnw.conf.j2
    dest: /etc/bird/bird4.peers.d/ffnw.conf
  notify:
    - configure bird
  tags: ffnw4

# bird config
- name: Ensure ffnw bgp4 kernel route filter is in place
  template:
    src: etc/bird/bird4.filters.d/mesh_kernel.d/050-ffnw-set-krt_prefsrc.export.j2
    dest: /etc/bird/bird4.filters.d/mesh_kernel.d/050-ffnw-set-krt_prefsrc.export
  notify:
    - configure bird
  tags: ffnw4

- name: Ensure ffnw bgp4 config defines are in place
  template:
    src: etc/bird/bird4.conf.d/020-ffnw-defines.conf.j2
    dest: /etc/bird/bird4.conf.d/020-ffnw-defines.conf
  notify:
    - configure bird
  tags: ffnw4

- name: Ensure ffnw bgp4 config is in place
  template:
    src: etc/bird/bird4.conf.d/200-ffnw.conf.j2
    dest: /etc/bird/bird4.conf.d/200-ffnw.conf
  notify:
    - configure bird
  tags: ffnw4

# Firewall
- name: Ensure ffnw-input firewall chain exists
  copy:
    src: etc/iptables.d/001-CHAINS_ffnw4
    dest: /etc/iptables.d/001-CHAINS_ffnw4
  notify:
    - restart firewall
  tags: ffnw4, firewall

- name: Ensure ffnw-input delegation is set up in input chain
  template:
    src: etc/iptables.d/100-device-ffnw4.j2
    dest: /etc/iptables.d/100-device-ffnw4
  notify:
    - restart firewall
  tags: ffnw4, firewall

- name: Ensure incoming BGP traffic is accepted
  copy:
    src: etc/iptables.d/500-Allow-bgp-ffnw4
    dest: /etc/iptables.d/500-Allow-bgp-ffnw4
  notify:
    - restart firewall
  tags: ffnw4, firewall

- name: Ensure SNAT is enabled on peering interfaces
  template:
    src: etc/iptables.d/910-SNAT-ffnw.j2
    dest: /etc/iptables.d/910-SNAT-ffnw
  notify:
    - restart firewall
  tags: ffnw4, firewall
