---

- name: stop, mask and disable selected services
  tags: [systemd]
  systemd:
    masked: yes
    state: stopped
    enabled: no
    name: "{{ item }}"
  loop: "{{ masked_services | default('[]') }}"
