---
- name: restart bird
  service:
    name: bird
    state: restarted

- name: configure bird
  shell: |
    birdc configure || systemctl restart bird
    birdc configure 2> /dev/null | grep -iq 'reconfigur'
