---
# Packages
- name: Ensure bird is installed
  apt:
    name: bird
    state: present
  notify:
    - restart bird
  tags: bgp4

# Create directories
- name: Ensure bird peer directory exists
  file:
    path: /etc/bird/bird4.peers.d
    state: directory
  notify:
    - restart bird
  tags: bgp4

# Create dynamic configs
- name: Ensure bird global defines exist
  template:
    src: etc/bird/bird4.conf.d/010-global.conf.j2
    dest: /etc/bird/bird4.conf.d/010-global.conf
  notify:
    - configure bird
  tags: bgp4

# Local site-internal peerings
- name: Ensure bird mesh peering config exists
  template:
    src: "{{ 'etc/bird/bird4.peers.d/{{ site.code }}.conf.j2' }}"
    dest: "/etc/bird/bird4.peers.d/{{ site.code }}.conf"
  notify:
    - configure bird
  tags: bgp4

- name: Ensure bird mesh defines exists
  template:
    src: "{{ 'etc/bird/bird4.conf.d/020-{{ site.code }}-defines.conf.j2' }}"
    dest: "/etc/bird/bird4.conf.d/020-{{ site.code }}-defines.conf"
  notify:
    - configure bird
  tags: bgp4

- name: Ensure bird mesh config exists
  template:
    src: "{{ 'etc/bird/bird4.conf.d/200-{{ site.code }}.conf.j2' }}"
    dest: "/etc/bird/bird4.conf.d/200-{{ site.code }}.conf"
  notify:
    - configure bird
  tags: bgp4

# Firewall
- name: Ensure firewall allows bgp traffic
  copy:
    src: etc/iptables.d/500-Allow-bird-ipv4
    dest: /etc/iptables.d/500-Allow-bird-ipv4
  notify:
    - restart firewall
  tags: bgp4, firewall
