---
# Packages
- name: Ensure bird is installed
  apt:
    name: bird
    state: present
  notify:
    - restart bird6
  tags: bgp6

# Create directories
- name: Ensure bird6 peer directory exists
  file:
    path: /etc/bird/bird6.peers.d
    state: directory
  notify:
    - restart bird6
  tags: bgp6

- name: Ensure bird6 filter directory exists
  file:
    path: /etc/bird/bird6.filters.d
    state: directory
  notify:
    - restart bird6
  tags: bgp6

- name: Ensure bird6 mesh kernel filter directory exists
  file:
    path: /etc/bird/bird6.filters.d/mesh_kernel.d
    state: directory
  notify:
    - restart bird6
  tags: bgp6

- name: Ensure bird6 kernel filter directory exists
  file:
    path: /etc/bird/bird6.filters.d/main_kernel.d
    state: directory
  notify:
    - restart bird6
  tags: bgp6

# Drop static config files
- name: Ensure bird6 mesh kernel table exists
  copy:
    src: etc/bird/bird6.conf.d/100-kernel-table-mesh.conf
    dest: /etc/bird/bird6.conf.d/100-kernel-table-mesh.conf
  notify:
    - configure bird6
  tags: bgp6

- name: Ensure bird6 main kernel table exists
  copy:
    src: etc/bird/bird6.conf.d/100-kernel-table-main.conf
    dest: /etc/bird/bird6.conf.d/100-kernel-table-main.conf
  notify:
    - configure bird6
  tags: bgp6


# Drop config files
- name: Ensure bird6 global defines exist
  template:
    src: etc/bird/bird6.conf.d/010-global.conf.j2
    dest: /etc/bird/bird6.conf.d/010-global.conf
  notify:
    - configure bird6
  tags: bgp6

- name: Ensure bird6 mesh peering config exists
  template:
    src: "{{ 'etc/bird/bird6.peers.d/{{ site.code }}.conf.j2' }}"
    dest: "/etc/bird/bird6.peers.d/{{ site.code }}.conf"
  notify:
    - configure bird6
  tags: bgp6

- name: Ensure bird6 mesh config exists
  template:
    src: "{{ 'etc/bird/bird6.conf.d/200-{{ site.code }}.conf.j2' }}"
    dest: "/etc/bird/bird6.conf.d/200-{{ site.code }}.conf"
  notify:
    - configure bird6
  tags: bgp6

- name: Ensure firewall allows bgp traffic
  copy:
    src: etc/iptables.d/500-Allow-bird-ipv6
    dest: /etc/iptables.d/500-Allow-bird-ipv6
  notify:
    - restart firewall
  tags: bgp6, firewall
