---
- name: Determine wether installed version of batman_adv is suitable
  shell: |
    min_version="{{ batman.version_min if "version_min" in hostvars[inventory_hostname].batman else "" }}"
    max_version="{{ batman.version_max if "version_max" in hostvars[inventory_hostname].batman else "" }}"
    version="{{ batman.version }}"

    version_leq() {
      IFS=.
      v1=($1)
      v2=($2)
      unset IFS
      len_v1=${{'{'}}#v1[@]}
      len_v2=${{'{'}}#v2[@]}
      len_min=$len_v1
      if [ $len_v2 -lt $len_min ]; then
        len_min=$len_v2
      fi

      for i in `seq 0 $((len_min - 1))`; do
        if {{ '[ ${v1[$i]} -lt ${v2[$i]} ]' }}; then
          return 0
        fi
        if {{ '[ ${v1[$i]} -gt ${v2[$i]} ]' }}; then
          return 1
        fi
      done

      return 0
    }

    modversion="$(modinfo batman_adv | grep "^version:" | sed "s/[[:space:]]\+/ /g" | cut -f2 -d" ")"
    if [ -n "$min_version" ] && version_leq "$modversion" "$min_version"; then
      echo dkms
      exit 0
    fi

    if [ -n "$max_version" ] && version_leq "$max_version" "$modversion"; then
      echo dkms
      exit 0
    fi

    if [ -z "$min_version" ] && [ -z "$max_version" ]; then
      if version_leq "$version" "$modversion" && version_leq "$modversion" "$version"; then
        echo distro
        exit 0
      fi
      echo dkms
      exit 0
    fi

    echo distro
  args:
    executable: /bin/bash
  register: batman_adv_src
  changed_when: no
  check_mode: no
  tags: batman_adv_dkms

- name: Install batman_adv (dkms)
  include_tasks: dkms.yml
  when: '"dkms" in batman_adv_src.stdout'
  tags: batman_adv_dkms

- name: Install batman_adv (distro)
  include_tasks: distro.yml
  when: '"distro" in batman_adv_src.stdout'
  tags: batman_adv_dkms
