---
# This playbook configures the basic, always required interfaces

# Install required packages
- name: Ensure required networking packages are installed
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - batctl
      - bridge-utils

# Interface setup
- name: ensure bridge interface is present
  template:
    src: etc/network/interfaces.d/bridge.j2
    dest: /etc/network/interfaces.d/br-{{ site.code }}
  notify:
    - restart mesh bridge
    - restart batman

- name: Ensure batman interface is present
  template:
    src: etc/network/interfaces.d/batman.j2
    dest: /etc/network/interfaces.d/bat-{{ site.code }}
  notify:
    - restart batman

- name: Ensure mesh bridge is up
  shell: ip link show br-{{ site.code }} || ifup br-{{ site.code }}
